### ISSUE TITLE
ERR_CONNECTION_REFUSED on CloudFormation PublicDNS

### ISSUE THREAD

**Issue by rsignell-usgs** [opendatacube/cube-in-a-box#17]
@alexgleith, I'm at USGS research scientist and a member of the [Pangeo community](pangeo.io).   At the US AWS Public Sector Summit last week in Washington DC I heard a lot about opendatacube and was excited to find out that ODC works with COGs on S3.  

After watching your awesome [ODC in a box video](https://www.youtube.com/watch?v=durO4PiqKsU), I tried the CloudFormation magic link following the [detailed AWS instructions](https://github.com/opendatacube/cube-in-a-box/blob/master/docs/Detailed_Install.md#detailed-amazon-web-services-aws-install-instructions).    

Everything seemed to go well: ![2019-06-18_8-21-51](https://user-images.githubusercontent.com/1872600/59681553-2ef44280-91a2-11e9-82de-9ff9b6d9b4b1.png)

But when I click the [publicDNS link](ec2-34-216-196-102.us-west-2.compute.amazonaws.com), I get:  ERR_CONNECTION_REFUSED.    

I'm guessing this is something simple like adding some extra policy somewhere, right?

**Comment by alexgleith** [comment]
Hey @rsignell-usgs, thanks for the issue here.

The local Docker Compose setup is a bit more reliable, and I'm fairly sure it will work.

But give me a bit of time and I'll have a look into what's going wrong here. The AWS deployment is a bit fragile... possibly needs a bit of attention and some redesign.

If you want to just have a play with the ODC, ping me at my github user at gmail and I'll send you a link to a testing instance we have!

**Comment by alexgleith** [comment]
Hey, this has been resolved. Give it a go using the magic link again! And let me know what you think. I'm keen to see how we can work with PanGeo!

**Comment by rsignell-usgs** [comment]
It's working!  
![2019-06-19_9-48-34](https://user-images.githubusercontent.com/1872600/59778028-b5cd1c00-9283-11e9-8662-fc7a7eb7f847.jpg)

**Comment by alexgleith** [comment]
Excellent!

Note that this is a trivial example (obviously) and that there are some much better case studies out there. It's really just a demonstration of the architecture of the ODC, and some of its potential.
